module.exports.config = {
  name: "kicktag",
  version: "1.0.0",
  hasPermssion: 3,
  Rent: 2,
  credits: "Vtuan",
  description: "Kick và tag người dùng cùng một lúc",
  commandCategory: "War",
  usages: "[@tag]",
  cooldowns: 5,
  envConfig: {
    kickTagDelay: 2 
  }
};

const kickTagThreads = new Set();
function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
module.exports.run = async function ({ api, event, args }) {
  const { threadID, messageID, senderID } = event;
  const botID = api.getCurrentUserID();
  const { adminIDs } = await api.getThreadInfo(event.threadID);
  let uid = Object.keys(event.mentions)[0];
  const isBotAdmin = adminIDs.some(adminInfo => adminInfo.id == botID);
  if (!isBotAdmin) {
    return api.sendMessage("Bot không phải là quản trị viên.", event.threadID, event.messageID);
  }
  const spamDelay = this.config.envConfig.kickTagDelay * 1000;
  let i = 0;
  if (args[0] === "stop") {
    if (kickTagThreads.has(threadID)) {
      kickTagThreads.delete(threadID);
      return api.sendMessage("Đã dừng kicktag!", threadID, messageID);
    } 
    return api.sendMessage("Không có quá trình kicktag nào đang diễn ra!", threadID, messageID);
  }
  if (!uid) {
    kickTagThreads.delete(threadID);
    return api.sendMessage("Bạn cần tag một người để kicktag.", threadID, messageID);
  }
  if (!kickTagThreads.has(threadID)) {
    kickTagThreads.add(threadID);
    api.sendMessage("Ỏ chào cậu nha!", threadID, messageID);
    while (kickTagThreads.has(threadID)) {
      const vtuann = [
        "Cayy",
        "Không cayy",
        "sủa đê 🤣🤣",
        "chó bú cứt🤣🤣👌",
        "hăng hái đê :)) ",
        "chậm dọ 🤣🤣 ",
        "óc dái cay r🤣🤣 ",
        "ăn hại phát biểu lẹ đê 🤣🤣 ",
        "óc dái :))) ",
        "ổn phải k? ",
        "ngu ớn 🤣🤣👌 ",
        "chó ăn cứt 🐶 ",
        "dái đú :)))) ",
        "yếu dữ ta😏😏 ",
        "con chó đần👉🤣 ",
        "ổn dữ chưa =))) ",
        "run ớn dạ :))) ",
        "óc đú 🤣🤣 ",
        "rồi xong 🤢🤢 ",
        "có thể hăng ko á  ",
        "ẻm cay doài =))) ",
        "cay tuột buồi 👉🤣",
        "ei ei =)) ",
        "em ei :3 ",
        "chạy à ",
        "mày sợ hả 🤢🤢 ",
        "coi ẻm sồn kìa🤣🤣 👌",
        "lại bá à :))) ",
        "sao chậm dữ ",
        "eo oyyy:3 ",
        "hú hú🤨 ",
        "sao ức chế dạ 😏😏 ",
        "con não cún bị chửi kìa 🤣🤣🐶 ",
        "mau đê :)) ",
        "hăng đê :))) ",
        "sủa mau đê =)) ",
        "cần cứu ko :)) ",
        "cố đi :3 ",
        "gáng lên đê :))) ",
        "sủa to lên🤣🤣 ",
        "phò nông thôn 🤢🤢 ",
        "óc cặc tỉnh lẽ =)))) ",
        "khoẻ ko 🤣🤣 ",
        "kkk ",
        "đói à🤣🐶👌 ",
        "ăn chưa à 🤣🤣 ",
        "chưa đk :))) ",
        "thấy kém cõi :)) ",
        "đú cứt kìa :))) ",
        "eo oyyy:3 ",
        "cố đê 🤣🤣 ",
        "thấy mày đơ đơ :))) ",
        "con cave 🤣🤣 ",
        "mạnh lên:))) ",
        "gõ mạnh lên đê:)) ",
        "thấy ngại ngùng z🤣🤘 ",
        "tự nhiên đê ",
        "mệt đk ",
        "cấm m ngưng ",
        "đĩ đầu đinh :))) ",
        "lẹ đê:)) ",
        "mày lag à :)) ",
        "m trầm cảm à :))) ",
        "tâm lí ko vững à :)) ",
        "cần thuốc à :)) ",
        "hấp hối hả🤣🤣 ",
        "khó thở dk :)) ",
        "cần oxi ko :))) ",
        "mày bệnh nặng lắm à :))) ",
        "tuột hứng cha :))) ",
        "tnh gà :))) ",
        "sao chậm chạp v :)) ",
        "óc dái 🤣🤣 ",
        "lồn cụ con đĩ đớ🤣🤣 ",
        "lưu loát lên đê 🤣🤣 ",
        "khựng dạ :))) ",
        "t mạnh lắm phải ko à :))) ",
        ":))) nhỏ mếu à ae ",
        "m nghèo mà ",
        "sợ t lắm à:3 ",
        "hả cu =))) ",
        "thấy tội quá:)) ",
        "thương ẻm cố gắng🤢🤘 ",
        "mà ngu🤣🤣 ",
        ":)) 🤣🤣 ",
        "cay lắm à :)) ",
        "nhạt nhoè v à ",
        "ko cảm hứng để hăng à :))) ",
        "xạo lồn à :))) ",
        "khóc đk :))) ",
        "cave tỉnh lẽ phát biểu:)) ",
        "ra tín hiệu đê :))) ",
        "SOS con dái đú 🤣🤣🤢 ",
        "ớ ớ ớ :))) ",
        "chó ăn cứt :))) ",
        "chó đú sàn 👌🐶 ",
        "ỉa ra máu r à :))) ",
        "nghèo k có nghi lực à:))",
        "phản kháng đê :))) t win à ",
        "kkk ",
        "m chết r à :))) ",
        "m nghèo mà em 😏🤣 ",
        "m thèm cứt t mà:)) ",
        "đĩ mẹ m ngu mà👉🤣 ",
        "m cay tao mà :)) ",
        "con óc cứt thối🤢🤢 ",
        "con đĩ mặt chim🤪🤪 ",
        "ôm hận à 🤨 ",
        "con đĩ nhà núi :))) ",
        "bede bóng lộ =)) ",
        "cn đĩ mẹ mày ",
        "tao từ hình mẹ m mà :)) ",
        "tk phế vật ăn hại😏🤘 ",
        "đú đởn hả con :)) ",
        "m sao dọ ",
        "sủa nè  ",
        "123 sủa😏 ",
        "lẹ nè  ",
        "alo alo hú hú  ",
        "th cầm thú ",
        "m s dạ  ",
        "m sợ mẹ hả  ",
        "lên đi mẹ ko giết cha má m đâu mà 😏 ",
        "hù :)) ",
        "bất ổn hở ",
        "s đó  ",
        "m rớt kìa th gà🤪 ",
        "t cấm m chối nhen ",
        "chối t giết cha má m nè:))) ",
        "hăng xíu lẹ kaka🤢 ",
        "th đần  ",
        "lên mẹ biểu ",
        "k lên t tuyệt chủng m nhen cn thú ",
        "m thích đú ko dạ🤨 ",
        "ko rep = t win nhen  ",
        "cấm chạy nhen ",
        "m mau  ",
        "lên đây ơ ơ  ",
        "th ngu ê ",
        "s á lên đây mẹ sút m chết ",
        "m khóc à 👉🤣",
        "sủa liên tục ơ🤣🤣 ",
        "cầu cứu lũ đú à  ",
        "sục dái nó xem à ",
        "dái thâm v? ",
        "chậm v cn culi🤣🤣👌 ",
        "hoảng loạn à ",
        "bất ổn à 🤮🤮 ",
        "run à ",
        "chạy à  ",
        "đuối à  ",
        "bại chưa 👉😏 ",
        "sủa mau🙄🙄👈 ",
        "mạnh dạn lên  ",
        "nhanh t cho cơ hội cứu má m nè ",
        "cấm mách mẹ ",
        "ảo war hở :)) ",
        "dồn ko  ",
        "đua nè lên sàn t chấp😏👌 ",
        "th chợ búa m sao v ",
        "th đầu buồi mặt chó😢🫵🏻👈🏻 ",
        "cấm hoảng loạn ",
        "lại phải win nữa à🙄🙄 ",
        "kkk ",
        "thằng bê đê bất lực vì mẹ nó bị đụ tung cái lồn:)))  ",
        "con đĩ mẹ mày bất lực vì bị tao chửi mà chỉ biết câm lặng:)))  ",
        "làm màu mà bị tao chửi rung cái con cặc:)))  ",
        "Mẹ mày bị tao đụ lòi hột le:)))  ",
        "thằng bê đê ảo cặc đòi cân và cái kết:)))  ",
        "con đĩ mẹ của mày thèm cứt tao dữ lắm:)))  ",
        "bị tao chửi sảng cặc đéo dám care:)))  ",
        "mạnh lên sao yếu đuối v con:)))  ",
        "mày run cặc chưa con:)))  ",
        "chậm vậy sao cứu được con đĩ mẹ mày nhanh lên đi chứ:)))  ",
        "chết cha nó sồn r  ",
        "con đĩ mẹ mày gào thét đê?😛  ",
        "mày gào lên con?😏  ",
        "sao cay tao dọ?  ",
        "mày sủa đi nè😛  ",
        "sao mày xấu lồn gớm chó dị con?  ",
        "sao cay tao hả😏?  ",
        "sao mày giết mẹ vậy=)))  ",
        "mày gào đi con=)))  ",
        "nào ổn thì đú🤣👈  ",
        "ê bê đê lên ăn hôi lẹ😘  ",
        "mày đú rõ mò  ",
        "sao mày ăn cứt tao😏  ",
        "ai cho mày ăn cứt tao  ",
        "sao mày óc cặc dữ con=)))  ",
        "gặp tao đừng run nha?😂  ",
        "con đĩ mẹ mày thèm cứt tao dữ lắm=)))  ",
        "mày mồ côi mà đúng k🤣👈  ",
        "ai cho mày sủa tao cho mày sủa chưa?  ",
        "bị tao chọc cay hơn con chó luôn=)))  ",
        "cố đi sắp win rồi nè😏  ",
        "chừng nào mày mới làm lại tao dị?  ",
        "mẹ mày sắp tắt thở kìa ê  ",
        "đậu má mày gà mà sủa  ",
        "sủa điên đi mà sủa hăng lên mới vui😘  ",
        "mày mà ngưng một giây là con đĩ mẹ mày bả tắt đường thở á😏  ",
        "ê chó ngu mày sợ tao hả😂  ",
        "mày đú rõ mà sao mày đú dị?  ",
        "mẹ mày chết chưa con=)))  ",
        "ê bê đê sủa điên đi  ",
        "sao mày sủa chậm dị?  ",
        "nào làm lại tao nói đê?  ",
        "bị tao chọc cay hơn con chó luôn😏  ",
        "sủa đi rồi tao tha?  ",
        "sủa điên lên cho mẹ?  ",
        "mày ngưng là con đĩ mẹ mày chết?  ",
        "cay tao lòi dái hả😏  ",
        "não chó cay à?🤣  ",
        "sao mày thảm dị=)))  ",
        "mẹ mày bị tao địt rách màn trinh mà🤪  ",
        "mẹ mày bị tao dã vào lồn=)))  ",
        "địt mẹ mày sướng tê con cặc=)))  ",
        "huhu nhìn mày như con cặc=)))  ",
        "mày loạn luân bà già hả=)))  ",
        "mẹ mày bị tao địt rên ư ử=)))  ",
        "địt mẹ mày sảng khoái quá đi😛  ",
        "tao địt mẹ mày nát lồn mà=)))  ",
        "Ê bóng lồn  ",
        "mẹ mày bị tao cưỡng hiếp=)))  ",
        "mẹ mày đưa lồn chó liếm à🤣👈  ",
        "mày óc cái lồn mà  ",
        "năn nỉ đi tao tha😏  ",
        "bú lồn tao đi🤪  ",
        "mày ẳng gì dị?😏  ",
        "nghe nói mày sợ tao?  ",
        "vô danh cấm sủa?😏 ",
        "gì mày thèm cứt tao hả=)))?  ",
        "sao mày lề mề dị con  ",
        "mày có tuổi hở?😏  ",
        "tuổi lồn ăn tao á😏?  ",
        "tao đụ má mày ná thở mà😛 ",
        "thg ngu va tí kh 🤣🤣 ",
        "vô danh cấm sủa?😏  ",
        "gì mày thèm cứt tao hả=)))?  ",
        "sao mày lề mề dị con  ",
        "mày có tuổi hở?😏  ",
        "tuổi lồn ăn tao á😏?  ",
        "tao đụ má mày ná thở mà😛 ",
        "cấm hoảng loạn ",
        "lại phải win nữa à🙄🙄 ",
        "kkk ",
        "tuột hứng cha :))) ",
        "tnh gà :))) ",
        "sao chậm chạp v :)) ",
        "óc dái 🤣🤣 ",
        "lồn cụ con đĩ đớ🤣🤣 ",
        "lưu loát lên đê 🤣🤣 ",
        "khựng dạ :))) ",
        "t mạnh lắm phải ko à :))) ",
        ":))) nhỏ mếu à ae ",
        "m nghèo mà ",
        "sợ t lắm à:3 ",
        "hả cu =))) ",
        "thấy tội quá:)) ",
        "thương ẻm cố gắng🤢🤘 ",
        "mà ngu🤣🤣 ",
        ":)) 🤣🤣 ",
        "cay lắm à :)) ",
        "nhạt nhoè v à ",
        "ko cảm hứng để hăng à :))) ",
        "xạo lồn à :))) ",
        "khóc đk :))) ",
        "cave tỉnh lẽ phát biểu:)) ",
        "ra tín hiệu đê :))) ",
        "SOS con dái đú 🤣🤣🤢 ",
        "ớ ớ ớ :))) ",
        "chó ăn cứt :))) ",
        "chó đú sàn 👌🐶 ",
        "ỉa ra máu r à :))) ",
        "nghèo k có nghi lực à:)) ",
        "phản kháng đê :))) t win à ",
        "sủa đê 🤣🤣 ",
        "chó bú cứt🤣🤣👌",
        "hăng hái đê :)) ",
        "chậm dọ 🤣🤣 ",
        "óc dái cay r🤣🤣 ",
        "ăn hại phát biểu lẹ đê 🤣🤣 ",
        "óc dái :))) ",
        "ổn phải k? ",
        "ngu ớn 🤣🤣👌 ",
        "chó ăn cứt 🐶 ",
        "dái đú :)))) ",
        "yếu dữ ta😏😏 ",
        "con chó đần👉🤣 ",
        "ổn dữ chưa =))) ",
        "run ớn dạ :))) ",
        "óc đú 🤣🤣 ",
        "rồi xong 🤢🤢 ",
        "có thể hăng ko á  ",
        "ẻm cay doài =))) ",
        "cay tuột buồi 👉🤣",
        "ei ei =)) ",
        "em ei :3 ",
        "chạy à ",
        "mày sợ hả 🤢🤢 ",
        "coi ẻm sồn kìa🤣🤣 👌",
        "lại bá à :))) ",
        "sao chậm dữ ",
        "eo oyyy:3 ",
        "hú hú🤨 ",
        "sao ức chế dạ 😏😏 ",
        "con não cún bị chửi kìa 🤣🤣🐶 ",
        "mau đê :)) ",
        "hăng đê :))) ",
        "sủa mau đê =)) ",
        "tuột hứng cha :))) ",
        "tnh gà :))) ",
        "sao chậm chạp v :)) ",
        "óc dái 🤣🤣 ",
        "lồn cụ con đĩ đớ🤣🤣 ",
        "lưu loát lên đê 🤣🤣 ",
        "khựng dạ :))) ",
        "t mạnh lắm phải ko à :))) ",
        ":))) nhỏ mếu à ae ",
        "m nghèo mà ",
        "sợ t lắm à:3 ",
        "hả cu =))) ",
        "thấy tội quá:)) ",
        "thương ẻm cố gắng🤢🤘 ",
        "mà ngu🤣🤣 ",
        ":)) 🤣🤣 ",
        "cay lắm à :)) ",
        "nhạt nhoè v à ",
        "ko cảm hứng để hăng à :))) ",
        "xạo lồn à :))) ",
        "khóc đk :))) ",
        "cave tỉnh lẽ phát biểu:)) ",
        "ra tín hiệu đê :))) ",
        "SOS con dái đú 🤣🤣🤢 ",
        "ớ ớ ớ :))) ",
        "chó ăn cứt :))) ",
        "chó đú sàn 👌🐶 ",
        "ỉa ra máu r à :))) ",
        "nghèo k có nghi lực à:)) ",
        "phản kháng đê :))) t win à ",
        "cần cứu ko :)) ",
        "cố đi :3 ",
        "gáng lên đê :))) ",
        "sủa to lên🤣🤣 ",
        "phò nông thôn 🤢🤢 ",
        "óc cặc tỉnh lẽ =)))) ",
        "khoẻ ko 🤣🤣 ",
        "kkk ",
        "đói à🤣🐶👌 ",
        "ăn chưa à 🤣🤣 ",
        "chưa đk :))) ",
        "thấy kém cõi :)) ",
        "đú cứt kìa :))) ",
        "eo oyyy:3 ",
        "cố đê 🤣🤣 "
      ];
      const content = vtuann[i % vtuann.length];
      await api.removeUserFromGroup(uid, threadID);
      await delay(500);
      api.addUserToGroup(uid, threadID, async (err) => {
        if (err) {
          kickTagThreads.delete(threadID);
          return api.sendMessage(`Lỗi khi thêm người dùng vào lại nhóm`, threadID, messageID);
        }
        await api.sendMessage({ body: `${content}`, mentions: [{ tag: content, id: uid }] }, threadID);
      });
      i++; 
      await delay(spamDelay);
    }
  } else {
    api.sendMessage("Chỉ thực hiện được 1 người!", threadID, messageID);
  }
};